spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ranchel
    url: jdbc:mysql://127.0.0.1:3306/food_project?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  http:
    encoding:
      force: true
      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates

    #  mvc:
    #   view:
    #     prefix: /WEB-INF/
    #     suffix: .jsp
    #  mvc:
    #   view:
    #     prefix: /templates/
    #     suffix: .ftl

server:
    context-path: /foodshop

sdk:
  alipay:
    dev: true
    sign-type: RSA2 #签名算法
    app-id: " 2018051460139538"
    private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCamUXl7PciN1yNMxZMeIndXsnsCGsTBGkqaWwphqZ0h7xF7xDs4frC2UWBu5qacrjn82zFCF2eZy0DdnO94sP/qA9hSvUQfG4dxGWMIcQx/nN7uEzQU7iFZHvq4PuYLrqF6io9QicQgXl0wGqLIhFPcHYunhqh8KmlNCBwnfXim/7Ptiu2Rv064Hc0ovrXQezfvD19uYbVdkuwB9QzSYvsXzMZa7fATsqtyhGP4qiBZQyQvB+ye1fZPCuG7HBvH7hHVDEAsVs9xgQab3QsaLdJ7qT70gFV9hiv087p6GLlTzMLGVt2GclvfjKa9Vm15zg6ieXm7x9El8FA+iCcF2p/AgMBAAECggEAMyibV83Frh3x04vfSijtPkMawK+8dwuTnYRLVaaIOLGeHOpSiIDzUT1C4f5p18g05hTInp75E+0CmU2+WUzMHTLI/CIo3G7ApbsS+39FBGI2Zu+DA8Fgo0uwMfaHa0GzWZM2rRTSBoVB4t+1ohsA7W/CvAR3vbT8/n00au/qqTT9uhmQukmMph+srychC/1TjaJoOlIfFaVPqowi1euKm3vL4hUUPeTleH50Udtl3TQJM9uB7U0SpCNxWaO8qM342FuiSVZNw6KRdJglRwJmuIiLPDYpPY5nP+doxrooPFwEzp4OxLtB28DnMVnUFG5yQqLc9jOFx4BKfQO5LrVC0QKBgQDx4auEeu1mVJ5EChcs4gTuY5Pz3eVVSHviFlS+Cr72TAWnxdd8xVsfl/3ekEgGD4hhHVXH2vMAzU6V53Gyichy6g5vlUT7eEmBBCqxGsAkkip/KEliimrteJpPpgs3mYtIOwKPjtoApIp5Krdgi3BPkiBostgtMd7GUOdxSfL5SQKBgQCjn1/PwfySgBOiV1h9JO9f1efuoM30wuI+0sCJ+EHdHOp2HZYpl8U50Xahyj13aTXq1FEJ9ZkgXdZP+gFy8aU1BfZRFxYebGtAysXhBsdZogsMEns6l3ecgoQ439jKSDWOKkaKVTfAHdIzZcV7TieNVrmM9iKJo+EaapBT2yNNhwKBgDvCxd21gXIG9hNZauBr90vuzl8yM7cecX0qh0Vs4kF4Bu2ss9Df8eOcadzTSPg2XjugQ9FdByzrjL78r9qssBm0OlzXRHPdBEwb+3BGa7KdamKAUaFHEaQaaAXFwH+8L+1opvlREguWm5/ULfpseRMvx1IW3dJMv/2/f28+FgoBAoGALS1A+A0Ynp6MTUOOpCcBjNVzz1hI5W61pyDrlmycSt/EAM7UejF0fC1QcwVzCThccbUjlvtfxycBmF1v7vu3YLd/tg4IxmerCV2zWxlTC3WJVVD5A0l09hq3RTjRE7DyUIltpp424W2abySHbS88DnNGkhwXlydPbMrFhNG5opsCgYEAxArLqIIAhyadzaBpZ6SCvWxB6dyJtcbbIOu41a4oUU8fn/iy6BVEwfF2kYxHqFGIW6zEqiQkeII+H/TTIZm4jZHXsLtWELlrqqrHdujFlzsX1/05L7TbvE7X/OVwn5HVb0D+NTgmSwjyn8YRgDxusoMp88MERt7F6Dp1+kYrHro="
    alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmplF5ez3IjdcjTMWTHiJ3V7J7AhrEwRpKmlsKYamdIe8Re8Q7OH6wtlFgbuamnK45/NsxQhdnmctA3ZzveLD/6gPYUr1EHxuHcRljCHEMf5ze7hM0FO4hWR76uD7mC66heoqPUInEIF5dMBqiyIRT3B2Lp4aofCppTQgcJ314pv+z7Yrtkb9OuB3NKL610Hs37w9fbmG1XZLsAfUM0mL7F8zGWu3wE7KrcoRj+KogWUMkLwfsntX2Twrhuxwbx+4R1QxALFbPcYEGm90LGi3Se6k+9IBVfYYr9PO6ehi5U8zCxlbdhnJb34ymvVZtec4Oonl5u8fRJfBQPognBdqfwIDAQAB"






